#!/bin/sh



SRC=syllabus.md
# POSIX-compliant substitution -- ${SRC//md/html} is zsh/bash-specific
DEST=${SRC%md}html

HTML="courses/2026-1-spring/123_core_concepts_in_cs/$DEST"

MD="/Users/ddrake1/google_drive/My Drive/teaching/2026-1-spring/123/$SRC"

if [ "$MD" -nt "$HTML" ]
then
    echo markdown is newer
    echo ---------
    printf "$SRC is newer than $DEST. Proceed with commit? "
    read -r CONTINUE
    if [ $CONTINUE = "y" ]
    then
        echo yes
        exit 0
    else
        echo Do:
        echo cd $(dirname $MD)
        echo make $DEST
        echo make publish
        exit 1
    fi
else
    echo markdown is NOT newer
fi
