remote_theme: pages-themes/hacker@v0.2.0
#theme: jekyll-theme-hacker
title: "dandrake.github.io"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
collections:
  assignments:
    output: true
    permalink: /courses/:path/
  cs101:
    output: true
    permalink: /courses/cs101/:name/
  "112": # need the quotes, Jekyll collections must be strings and
  # without quotes, Ruby types it as a string -> downstream string
  # methods fail
    output: true
    permalink: /courses/2026-1-spring/1122_intro_to_data_sci/:name/
  cs202:
    output: true
    permalink: /courses/cs202/:name/
